version: "3"

services:
    redis:
        image: library/redis:4
        container_name: redis
        ports: [
        "6379:6379"
        ]
    rabbit:
        container_name: rabbit-master-workers
        image: rabbitmq
        ports: 
        - "5672:5672"
        - "5673:5673"
        - "15672:15672"